### ISSUE TITLE
Room: the twink hole

### ISSUE THREAD

**Issue by boreq** [freeside-network/freeside-station-rc3#18]
- [x] base room
- [x] "The Twink Hole" sign
- [ ] extra signage

**Comment by lovelaced** [comment]
review please: 

![twinkhole](https://user-images.githubusercontent.com/8581604/102723437-2e44eb00-4308-11eb-9986-5d4fe50da18e.png)

This is with a black bg, the actual sign is transparent bg

**Comment by lovelaced** [comment]
![twinkhole_on](https://user-images.githubusercontent.com/8581604/102723503-af9c7d80-4308-11eb-8caa-200a8ede73b7.png)
![twinkhole_off](https://user-images.githubusercontent.com/8581604/102723504-b0351400-4308-11eb-895f-69e3c83ceee0.png)

**Comment by lovelaced** [comment]
closed with #21

**Comment by lovelaced** [comment]
![penis_on_2](https://user-images.githubusercontent.com/8581604/102724081-2fc4e200-430d-11eb-8e50-58ee13f7d534.png)
![penis_off_2](https://user-images.githubusercontent.com/8581604/102724082-305d7880-430d-11eb-9b53-b5b1c966d0ab.png)

//cc @boreq  for review

**Comment by boreq** [comment]
> ![penis_on_2](https://user-images.githubusercontent.com/8581604/102724081-2fc4e200-430d-11eb-8e50-58ee13f7d534.png)
> ![penis_off_2](https://user-images.githubusercontent.com/8581604/102724082-305d7880-430d-11eb-9b53-b5b1c966d0ab.png)
> 
> //cc @boreq for review

Not very subtle imo.

**Comment by boreq** [comment]
Updated it slightly.
